# Generated by Django 4.2.3 on 2023-07-25 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_model_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendororders',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororders',
            name='customer_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororders',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
