# Generated by Django 4.2.3 on 2023-07-25 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orders_date_vendororders_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 17, 26, 0, 966754, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 17, 26, 0, 966754, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vendororders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 17, 26, 0, 966754, tzinfo=datetime.timezone.utc)),
        ),
    ]
