# Generated by Django 4.2.3 on 2023-07-25 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_offers_date_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 17, 41, 32, 566387, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 17, 41, 32, 565392, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vendororders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 25, 17, 41, 32, 568387, tzinfo=datetime.timezone.utc)),
        ),
    ]
