# Generated by Django 4.2.3 on 2023-07-27 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_offers_date_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororders',
            name='cancelled_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 1, 47, 46, 56397, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 1, 47, 46, 56397, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vendororders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 1, 47, 46, 61240, tzinfo=datetime.timezone.utc)),
        ),
    ]
