# Generated by Django 4.2.3 on 2023-07-27 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_vendororders_cancelled_status_alter_offers_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancelled_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 2, 35, 0, 569312, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 2, 35, 0, 569312, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vendororders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 27, 2, 35, 0, 574313, tzinfo=datetime.timezone.utc)),
        ),
    ]
