# Generated by Django 4.2.3 on 2023-07-28 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_orders_cancelled_status_alter_offers_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='checkout_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 28, 20, 4, 50, 540773, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 28, 20, 4, 50, 540773, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vendororders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 28, 20, 4, 50, 545951, tzinfo=datetime.timezone.utc)),
        ),
    ]
