# Generated by Django 4.2.3 on 2023-08-02 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_orders_secret_alter_offers_date_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 2, 11, 46, 5, 424652, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 2, 11, 46, 5, 423655, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vendororders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 2, 11, 46, 5, 427650, tzinfo=datetime.timezone.utc)),
        ),
    ]
