# Generated by Django 4.1.10 on 2023-08-26 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_offers_date_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 26, 19, 46, 22, 303962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 26, 19, 46, 22, 303962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vendororders',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 26, 19, 46, 22, 306952, tzinfo=datetime.timezone.utc)),
        ),
    ]
